/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";

import * as SkeletonUtils from "three/examples/jsm/utils/SkeletonUtils";

export default function Model({ ...props }) {
  const group = useRef();
  const { scene, materials, animations } = useGLTF("/viking.gltf");
  const { actions } = useAnimations(animations, group);

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone);

  useEffect(() => {
    actions.walking.play();
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="viking_C_position"
        position={[0, 0.01, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <primitive object={nodes.Hips_vC_green} />
        <skinnedMesh
          name="viking_C"
          geometry={nodes.viking_C.geometry}
          material={materials.viking_C_texture}
          skeleton={nodes.viking_C.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/viking.gltf");
