/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/viking.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="viking_C_position" position={[0, 0.01, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.Hips_vC_green} />
        <skinnedMesh
          name="viking_C"
          geometry={nodes.viking_C.geometry}
          material={materials.viking_C_texture}
          skeleton={nodes.viking_C.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/viking.gltf')
